### ISSUE TITLE
ReplyError: ERR wrong number of arguments for 'set' command

### ISSUE THREAD

**Issue by theromie** [trulymittal/API-Authentication-NodeJs#2]
I created separate file to test REDIS SET method but sending error of wrong argument.

```
const client = require('./config/redis_config');
client.SET(1, "test", 'EX', 3 * 24 * 60 * 60, (err, reply) => {
  if (err) {
    console.log(err);
    return;
  }
  return reply;
});
```

If I remove EX and TTL it works fine.

**Comment by trulymittal** [comment]
1. Please share your **complete error log** that you are getting inside the console.
2. **Update** your Redis server.
3. If you are running **Redis on Windows**, then you are bound to get errors, this is a Redis issue - update the Redis version for windows.
4. Lastly, I am not getting what this `return reply` is doing there?

**Comment by theromie** [comment]
I am running **Redis on window** and I am using **SETEX** to expire which is working fine.
2 - Ignore **return reply**
