### ISSUE TITLE
Redis connection lost and command aborted. It might have been processed

### ISSUE THREAD

**Issue by theromie** [trulymittal/API-Authentication-NodeJs#5]
I have deployed API on another server and Redis on another server and connect each server for Redis but after some time like 10min or so if I try to access Redis data from API it's giving me **AbortError: Redis connection lost and command aborted. It might have been processed** but on local it's working fine.

**Comment by trulymittal** [comment]
Most likely the redis server issue:
visit this link for resolution: https://github.com/NodeRedis/node-redis/issues/1533

**Comment by theromie** [comment]
I don't know whether this is correct or not but Azure VMs Load balancer Idle timeout set to 4mins and after that, if API tries to hit Redis server for data that time it shows this error.

**Comment by trulymittal** [comment]
> I don't know whether this is correct or not but Azure VMs Load balancer Idle timeout set to 4mins and after that, if API tries to hit Redis server for data that time it shows this error.

This has nothing to with the application, it's a problem of how redis is configured with azure vm, fixing the vm timeout issue should solve the issue.

**Comment by theromie** [comment]
Correct, Thanks for your time.

**Comment by LightKnight3r** [comment]
@theromie did you solve this? Can you show me more detail
