### ISSUE TITLE
Can you please help me with the client code.

### ISSUE THREAD

**Issue by sourikghosh** [trulymittal/API-Authentication-NodeJs#7]
github [repo](https://github.com/sourikghosh/login_auth)
Can you please help me with the client side code that will fetch the /login api and set the Auth header in HttpRequest

**Comment by sourikghosh** [comment]
I wanted to create a new Discussion but unfortunately, it's not enabled in this repo...
I wanted to implement Axios but don't know the workflow how it will fetch and set the headers properly

**Comment by sourikghosh** [comment]
[Client Logic](https://github.com/sourikghosh/login_auth/tree/dev/src/clientLogic)

**Comment by trulymittal** [comment]
for web app, you can use axios, and use interceptors for the same.
